# Generated by Django 5.0.6 on 2024-05-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_human_delete_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
